# site name
prefixName: Eutopun's Blog
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/avatar.jpg
url: https://Eutopun.github.io
description: 且听风吟，静待花开
farewell: 愿过客爱你所爱，行你所行，听从你心，无问西东 # 如果以后再也见不到你，那祝你早安，午安，晚安。
meetion: 知足且坚定，温柔且上进
cdn: https://cdn.jsdelivr.net/gh/Eutopun/CDN@v0.80
pjax: 1
# 1开启
mathjax: 0

notice: 博主技术有限，博客正在缓慢更新中 ...
lazyloadImg: https://cdn.jsdelivr.net/gh/Eutopun/CDN@v0.80/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    目录: {path: /catalogue/, fa: fa-align-left faa-tada }
    # 技术: {path: /categories/技术/, fa: fa-code faa-shake }, 
    # 生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    # 资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    # 随想: {path: /categories/随想/, fa: fa-commenting-o faa-tada },
    # 转载: {path: /categories/转载/, fa: fa-book }
  } }
  日常: { path: javascript:;, fa: fa-coffee faa-shake, submenus: { 
    # 书单: {path: /tags/悦读/, fa: fa-th-list faa-vertical }, 
    影漫: {path: /bangumi/, fa: fa-film faa-float }, 
    歌单: {path: /music/, fa: fa-music faa-tada }
    # 图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-wrench }
  # 赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-angellist faa-tada}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura faa-tada },
  } }
  # 客户端: { path: /client/, fa: fa-android faa-vertical }
  # RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/Eutopun/CDN@v0.80/img/cover/background_day.png
  - https://cdn.jsdelivr.net/gh/Eutopun/CDN@v0.80/img/cover/background_night.png

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dim

# startdash url, title, desc img
startdash: 
- {url: /, title: Joe, desc: 博主技术不行，暂留开发, img: /img/startdash/nothing.jpg}



# your site build time or founded date
siteBuildingTime: 07/23/2020

#social  url, img PC端配置
social:
  email: {url: mailto:1142541404@qq.com, img: /img/social/email.png}
  github: {url: https://github.com/Eutopun, img: /img/social/github.png}
  wechat: {url: /#, qrcode: /img/custom/wechat.png, img: /img/social/wechat.png}
  qq: {url: tencent://message/?Menu=yes&uin=1142541404&Service=300&sigT=45a1e5847943b64c6ff3990f8a9e644d2b31356cb0b4ac6b24663a3c8dd0f8aa12a595b1714f9d45, img: /img/social/qq.png}
  bilibili: {url: https://space.bilibili.com/370410126, img: /img/social/bilibili.png}
  RSS: {url: /atom.xml, img: /img/social/RSS.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/Eutopun, fa: fa-github, color: 504b4d}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=1142541404&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}


donate:
  alipay: /img/donate/AliPay.png
  wechat: /img/donate/WeChatPay.png

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2480591250
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: 6Sn1gcrfDJlzgUG9l2vJcezV-gzGzoHsz
v_appKey: B68gAxKikDDY5HibFnUsvEAE

bg_music: https://cdn.jsdelivr.net/gh/Eutopun/CDN@v0.80/music/DreamWorld.mp3